# Generated by Django 2.2 on 2020-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileWallet2020', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
